maps:
  example_map:
    spawns: "100 20 400, 200 30 400..."
    name: "Example"
  example_map2:
    spawns: "100 20 400, 200 30 400..."
    name: "Example"
  example_map3:
    spawns: "100 20 400, 200 30 400..."
    name: "Example"

kits:
  example_kit_name:
    name: "Kit Name"
    items:
      1:
        material: "DIAMOND_SWORD"
        ammount: 1
        enchantments: "SHARPNESS 1, SWEEPING_EDGE 2"
      2:
        material: "DIAMOND_SHOVEL"
        ammount: 1
        enchantments:
    cost: 2
    position: 0

sign_pos: "0 0 0"